typography_spectrum: 0.25374932843260467
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.09508428280241787
  lightness: 0.3174024955369532
  rhythmicContrast: 0.30899402289651334
  saturation: 0.7133837845176458
github: true
layout_spectrum: 0.6966878820676357
name: Bedtime for Big Oil
url: 'http://www.bedtimeforbigoil.org'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3.amazonaws.com/upload.mural.ly/exploros/1426326410446/4-1427558193317?AWSAccessKeyId=AKIAIS6S6EJOS4UEIDLA&Expires=1742918204&Signature=USciJ2RD8mYnJp8HsvhwfztX3qM%3D">
    src: >-
      https://s3.amazonaws.com/upload.mural.ly/exploros/1426326410446/4-1427558193317?AWSAccessKeyId=AKIAIS6S6EJOS4UEIDLA&Expires=1742918204&Signature=USciJ2RD8mYnJp8HsvhwfztX3qM%3D
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3.amazonaws.com'
        name: .s3.amazonaws.com
        favicon: null
        domain: s3.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Bedtime for Big Oil
description: ''
